version: "3"

services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: redcup_recorder
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data_container:
